#!/bin/bash
set -e

function test_mount() {
    mount | grep /mnt/archinstall
}

function prompt_device_file() {
    while :; do
        echo
        read -p "$1 (/dev/?): " DEVICE_NAME
        DEVICE_FILE="/dev/$DEVICE_NAME"
        if [ -b "$DEVICE_FILE" ]; then
            break
        elif [ -z "$DEVICE_NAME" ]; then
            return 1
        else
            echo 'Invalid name!'
        fi
    done
}

lsblk

if [ ! -z "$(test_mount)" ]; then
    test_mount
    read -p 'Already mounted /mnt/archinstall as root, keep it? (Y/n) ' r
    [[ "$r" =~ ^(N|n)$ ]] &&
        umount -R /mnt/archinstall
fi

if [ -z "$(test_mount)" ]; then
    mkdir -p /mnt/archinstall
    prompt_device_file 'which mount to /mnt/archinstall' &&
        mount "$DEVICE_FILE" /mnt/archinstall
fi

if prompt_device_file 'which mount to /mnt/archinstall/boot'; then
    mkdir -p /mnt/archinstall/boot
    mount "$DEVICE_FILE" /mnt/archinstall/boot

    if prompt_device_file 'which mount to /mnt/archinstall/boot/efi'; then
        mkdir -p /mnt/archinstall/boot/efi
        mount "$DEVICE_FILE" /mnt/archinstall/boot/efi
    fi
fi

echo
echo 'mount | grep /mnt :'
mount | grep /mnt
