#!/bin/bash
set -e
cd /mnt/archinstall

arch-chroot . sed -i "/^#zh_CN.U/ s/^#//" /etc/locale.gen
arch-chroot . locale-gen

pacstrap . reflector
cp /etc/xdg/reflector/reflector.conf ./etc/xdg/reflector/reflector.conf
cp /etc/pacman.d/mirrorlist ./etc/pacman.d/mirrorlist
pacstrap . noto-fonts-cjk

[ "$(arch-chroot . pacman -Qs '^gnome$')" ] &&
    arch-chroot . pacman -Rns --noconfirm gnome-weather gnome-maps

[ "$(arch-chroot . pacman -Qs firefox)" ] &&
    pacstrap . firefox-i18n-zh-cn || :
