#!/bin/bash
set -e

DEVUTIL_PKGS=(git base-devel man-db unzip tree)

# Whiptail auto-size
WT_MENU_HEIGHT=6
WT_HEIGHT=$((WT_MENU_HEIGHT + 7 + 10))
WT_WIDTH=$(tput cols)
[ -z "$WT_WIDTH" ] || [ "$WT_WIDTH" -ge 68 ] && WT_WIDTH=68

choice=$(whiptail --clear --title 'Arch Linux - Postinstall Options' \
    --checklist "
    *  add WinOS to GRUB:
       for dual os
    *  optimize GRUB:
       remember selection & reduce wait time & better theme
    *  enlarge console font:
       keep 2x font size in tty permanently
    *  add development utils:
       $DEVUTIL_PKGS
    *  add Cascadia Code font:
       for coding or terminal-used
" $WT_HEIGHT $WT_WIDTH $WT_MENU_HEIGHT \
    'add WinOS to GRUB' '' OFF \
    'optimize GRUB' '' ON \
    'enlarge console font' '' ON \
    'add Firefox browser' '' ON \
    'add development utils' '' ON \
    'add Cascadia Code font' '' ON \
    3>&1 1>&2 2>&3)

echo
echo 'Testing fastest mirror ...'
systemctl restart reflector
echo

cd /mnt/archinstall

pacstrap . lsb-release noto-fonts-emoji gufw
[ "$(arch-chroot . pacman -Qs konsole)" ] && pacstrap . yakuake
[ -d usr/share/discover ] && pacstrap . packagekit-qt5 || :

case "$choice" in
*"add WinOS to GRUB"*)
    arch-chroot . sed -i '/^#GRUB_DISABLE_OS_PROBER/ s/^#//' /etc/default/grub
    pacstrap . os-prober ntfs-3g
    ;;&
*"optimize GRUB"*)
    #:
    arch-chroot . sed -i "/GRUB_DEFAULT/ s/=.*/=saved/" /etc/default/grub
    arch-chroot . sed -i '/GRUB_SAVEDEFAULT/ s/^#//' /etc/default/grub
    #:
    arch-chroot . sed -i "/GRUB_TIMEOUT/ s/=.*/=2/" /etc/default/grub
    #:
    pacstrap . breeze-grub
    echo 'GRUB_THEME=/boot/grub/themes/breeze/theme.txt' | tee -a etc/default/grub &>/dev/null
    pushd usr/share/grub/themes/breeze
    cp -n theme.txt theme.txt.old
    sed -i \
        -e '/# title/,/}/{/top/s/225.*/256/}' \
        -e '/+ boot_menu {/,/}/{s/400/800/;s/200/400/;/item_height =/s/33/64/;/font =/s/16/32/}' \
        -e '/+ vbox {/,/^}/{/top =/s/+113.*/+200/;s/"Unifont Regular 14"/"Unifont Regular 16"/}' \
        theme.txt
    popd
    ;;&
*"enlarge console font"*)
    pacstrap . terminus-font
    echo 'FONT=ter-i32b' | tee -a etc/vconsole.conf
    ;;&
*"add Firefox browser"*)
    pacstrap . firefox
    arch-chroot . cp /usr/share/applications/firefox.desktop /usr/share/applications/firefox-wayland.desktop
    arch-chroot . sed -i -e 's/^Name=Firefox$/Name=Wayland Firefox/' -e 's/^Exec=/Exec=env MOZ_ENABLE_WAYLAND=1 /' /usr/share/applications/firefox-wayland.desktop
    if (whiptail --title ' Firefox extensions? ' --yesno '  add recommended:\n
- Dark Reader
- decentraleyes
- uBlock Origin
- Tree Style Tab
' 12 26); then
        pacstrap . firefox-dark-reader firefox-decentraleyes firefox-ublock-origin firefox-tree-style-tab
    fi
    ;;&
*"add development utils"*)
    pacstrap . "${DEVUTIL_PKGS[@]}"
    ;;&
*"add Cascadia Code font"*)
    pacstrap . ttf-cascadia-code
    ;;&
esac
