#!/bin/bash
set -e
cd /mnt/archinstall

pacstrap . noto-fonts-cjk reflector
arch-chroot . sed -i "/^#zh_CN.U/ s/^#//" /etc/locale.gen
arch-chroot . locale-gen
arch-chroot . sed -i '/^--sort/ s/age/rate/' /etc/xdg/reflector/reflector.conf
echo "-c cn" | arch-chroot . tee -a /etc/xdg/reflector/reflector.conf &>/dev/null
arch-chroot . systemctl restart reflector
arch-chroot . pacman -Sy

[ "$(arch-chroot . pacman -Qs '^gnome$')" ] &&
    arch-chroot . pacman -Rns --noconfirm gnome-weather gnome-maps

[ "$(arch-chroot . pacman -Qs firefox)" ] &&
    pacstrap . firefox-i18n-zh-cn || printf ''
