#!/usr/bin/bash
set -e
cd $(dirname $0)

source ./lib/loadcfg
source ./lib/checkcfg

./lib/prefix

archinstall --config ./user_configuration.json

./lib/postrun/base
./lib/postrun/etc
./lib/postrun/grub
./lib/postrun/gnome
./lib/postrun/kde
./lib/postrun/fcitx
./lib/postrun/firefox
./lib/postrun/development
./lib/postrun/others

cd /mnt/archinstall
genfstab -U . >etc/fstab
arch-chroot . mkinitcpio -P
arch-chroot . grub-install --target=x86_64-efi --efi-directory=boot/efi --bootloader-id=GRUB
arch-chroot . grub-mkconfig -o boot/grub/grub.cfg
