#!/usr/bin/bash
echo '== Check Config =='
echo 'Edit `./config*` before setup. Reference: `./samples/*`'
echo
echo UPDATE_MIRROR=$UPDATE_MIRROR
echo
echo SETC_FASTER_SHUTDOWN=$SETC_FASTER_SHUTDOWN
echo SETC_LARGE_CFONT=$SETC_LARGE_CFONT
echo
echo GRUB_OPTIMZE=$GRUB_OPTIMZE
echo GRUB_USE_BETTER_THEME=$GRUB_USE_BETTER_THEME
echo GRUB_ADD_WINBOOT_AUTO=$GRUB_ADD_WINBOOT_AUTO
echo
echo ADD_TLP=$ADD_TLP
echo
echo ADD_DEVELOPMENT=$ADD_DEVELOPMENT
echo
echo ADD_FIREFOX=$ADD_FIREFOX
echo ADD_FIREFOX_EXT=$ADD_FIREFOX_EXT
echo
echo ADD_QBITTORRENT=$ADD_QBITTORRENT
echo ADD_DEJADUP=$ADD_DEJADUP
echo
echo IS_REGION_IN_CHINA=$IS_REGION_IN_CHINA
echo ADD_FCITX5=$ADD_FCITX5
echo
printf 'Confirm to setup? (Y/n) '
read r
case $r in
'' | y | Y) ;;
*) exit ;;
esac
