#!/usr/bin/bash
set -e
cd /mnt/archinstall

list=()

if [ "$ADD_VLC" = 1 ]; then
    list+=('vlc')
fi

if [ "$ADD_DEJADUP" = 1 ]; then
    list+=('deja-dup')
fi

if [ "$ADD_QBITTORRENT" = 1 ]; then
    list+=('qbittorrent')
fi

pacstrap . ${list[*]}
